apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract-frontend
  template:
    metadata:
      labels:
        app: contract-frontend
    spec:
      containers:
        - name: frontend
          image: contract-frontend:latest
          ports:
            - containerPort: 80
